(function(){
  'use strict';
  var orders=[],active=null,filter='all';
  function esc(v){var d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
  function date(v){if(!v)return null;if(typeof v.toDate==='function')return v.toDate();if(v.seconds)return new Date(v.seconds*1000);return new Date(v)}
  function money(v){return'TTD $'+Number(v||0).toFixed(2)}
  function label(v){return String(v||'pending').replace(/_/g,' ').replace(/\b\w/g,function(c){return c.toUpperCase()})}
  function count(o){return(o.items||[]).reduce(function(s,i){return s+Number(i.quantity||1)},0)}
  function paymentStatus(o){return o.paymentStatus||(o.payment&&o.payment.status)||'pending'}
  function render(){
    var q=(document.querySelector('.topbar-search input')?.value||'').toLowerCase();
    var list=orders.filter(function(o){var hay=[o.orderNumber,o.customerName,o.customerEmail,o.customerPhone].join(' ').toLowerCase();return(filter==='all'||o.status===filter)&&(!q||hay.includes(q))});
    ['all','pending','fulfilled','cancelled'].forEach(function(s){var el=document.getElementById(s+'Count');if(el)el.textContent=s==='all'?orders.length:orders.filter(function(o){return o.status===s}).length});
    document.getElementById('ordersBody').innerHTML=list.length?list.map(function(o){var created=date(o.createdAt),pay=paymentStatus(o);return '<tr class="order-row"><td><strong>#'+esc(o.orderNumber||o.firestoreId)+'</strong></td><td>'+esc(o.customerName||(o.customer&&o.customer.name)||'—')+'<small class="order-cell-sub">'+esc(o.customerEmail||(o.customer&&o.customer.email)||'')+'</small></td><td>'+count(o)+'</td><td><strong>'+money(o.total||(o.pricing&&o.pricing.total))+'</strong></td><td><span class="badge '+(pay==='paid'||pay==='verified'||pay==='payment_confirmed'?'success':'pending')+'">'+esc(label(pay))+'</span></td><td><span class="badge '+(o.status==='fulfilled'?'success':o.status==='cancelled'?'danger':'pending')+'">'+esc(label(o.status))+'</span></td><td>'+esc(created?created.toLocaleString('en-TT',{dateStyle:'medium',timeStyle:'short'}):'Pending sync')+'</td><td><button class="btn btn-sm btn-primary" data-live-action="view" data-id="'+esc(o.firestoreId)+'">View</button></td></tr>'}).join(''):'<tr><td colspan="8"><div class="admin-empty-state"><h3>No orders found</h3><p>New customer orders will appear here automatically.</p></div></td></tr>';
  }
  async function drawer(o){
    active=o;var c=o.customer||{},del=o.delivery||{},pay=o.payment||{},p=o.pricing||{},created=date(o.createdAt);var map=del.latitude&&del.longitude?'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(del.latitude+','+del.longitude):'';
    var history=[];try{var snap=await db.collection('inventoryTransactions').where('orderId','==',o.firestoreId).get();snap.forEach(function(d){history.push(d.data())})}catch(e){console.warn('Inventory history unavailable',e)}
    var items=(o.items||[]).map(function(i){var original=Number(i.baseUnitPrice||i.unitPrice||0),sale=Number(i.unitPrice||0),discount=original>sale?'<small><s>'+money(original)+'</s> · '+Number(i.discountRate||0)+'% off</small>':'';return '<div class="order-item"><div class="order-item-thumb">'+(i.image?'<img src="'+esc(i.image)+'" alt="">':'<i class="fas fa-seedling"></i>')+'</div><div class="item-info"><div class="item-name">'+esc(i.productName||i.name)+'</div><small>'+esc(i.category||'Plant')+' · '+money(sale)+' each</small>'+discount+'</div><div class="item-quantity">×'+Number(i.quantity||1)+'</div><div class="item-price">'+money(i.lineTotal||sale*Number(i.quantity||1))+'</div></div>'}).join('');
    var events=history.length?history.map(function(h){return '<div class="inventory-event"><i class="fas fa-boxes-stacked"></i><div><strong>'+esc(label(h.type))+'</strong><span>'+esc(h.productName)+' · '+(Number(h.adjustment)>0?'+':'')+Number(h.adjustment||0)+' ('+h.before+' → '+h.after+')</span></div></div>'}).join(''):'<p class="order-muted">No inventory events recorded for this order.</p>';
    var invoiceEmail=o.invoiceEmail||{status:'not_sent'},sent=date(invoiceEmail.sentAt);var invoiceMeta='<p><strong>Invoice email:</strong> <span class="badge '+(invoiceEmail.status==='sent'?'success':invoiceEmail.status==='failed'?'danger':'pending')+'">'+esc(label(invoiceEmail.status||'not_sent'))+'</span></p>'+(invoiceEmail.recipient?'<p>Sent to: '+esc(invoiceEmail.recipient)+'</p>':'')+(sent?'<p>Sent: '+esc(sent.toLocaleString('en-TT',{dateStyle:'medium',timeStyle:'short'}))+'</p>':'');
    document.getElementById('orderDrawerBody').innerHTML='<div class="order-details"><div class="order-header"><div><span class="admin-eyebrow">Order</span><h4>#'+esc(o.orderNumber||o.firestoreId)+'</h4><small>'+esc(created?created.toLocaleString('en-TT',{dateStyle:'full',timeStyle:'short'}):'Pending sync')+'</small></div><span class="badge '+(o.status==='cancelled'?'danger':o.status==='fulfilled'?'success':'pending')+'">'+esc(label(o.status))+'</span></div><div class="order-detail-grid"><section class="order-section"><h5>Customer</h5><p><strong>'+esc(o.customerName||c.name)+'</strong></p><p>'+esc(o.customerEmail||c.email)+'</p><p>'+esc(o.customerPhone||c.phone)+'</p></section><section class="order-section"><h5>Payment & invoice</h5><p><strong>'+esc(label(o.paymentMethod||pay.method))+'</strong></p><p><span class="badge '+(paymentStatus(o)==='payment_confirmed'?'success':'pending')+'">'+esc(label(paymentStatus(o)))+'</span></p>'+invoiceMeta+(pay.proofReference?'<p>Proof submitted</p>':'')+'</section><section class="order-section"><h5>Delivery</h5><p><strong>'+esc(label(del.method||o.deliveryOption))+'</strong></p><p>'+esc([del.address||o.address,del.city||o.city,del.region||o.region].filter(Boolean).join(', ')||'Farm pickup')+'</p>'+(map?'<a class="btn btn-sm btn-secondary" href="'+map+'" target="_blank" rel="noopener">Open map</a>':'')+'</section><section class="order-section"><h5>Fulfilment</h5><p>Status: <strong>'+esc(label(o.status))+'</strong></p><p>'+esc(o.notes||'No order notes.')+'</p></section></div><section class="order-section"><h5>Items</h5>'+items+'</section><div class="order-total"><div><span>Subtotal</span><span>'+money(p.subtotal||o.subtotal)+'</span></div><div><span>Promotion savings</span><span>−'+money(p.discount||o.discount)+'</span></div><div><span>Delivery</span><span>'+money(p.delivery||o.deliveryFee)+'</span></div><div class="total"><span>Total</span><span>'+money(p.total||o.total)+'</span></div></div><section class="order-section"><h5>Inventory history</h5>'+events+'</section></div>';
    var footer=document.querySelector('#order-details-drawer .drawer-footer');footer.innerHTML='<button type="button" class="btn btn-secondary drawer-close">Close</button><button type="button" class="btn btn-secondary" data-live-action="invoice"><i class="fas fa-file-pdf"></i> Download Invoice</button><button type="button" class="btn btn-secondary" data-live-action="email-invoice"><i class="fas fa-envelope"></i> '+(invoiceEmail.status==='sent'?'Resend':'Email')+' Invoice</button>'+(paymentStatus(o)!=='payment_confirmed'?'<button type="button" class="btn btn-primary" data-live-action="confirm-payment"><i class="fas fa-money-check"></i> Confirm Payment</button>':'')+(o.status==='pending'?'<button type="button" class="btn btn-danger" data-live-action="cancel"><i class="fas fa-ban"></i> Cancel Order</button><button type="button" class="btn btn-success" data-live-action="fulfill"><i class="fas fa-check"></i> Fulfil Order</button>':'');
    document.getElementById('order-details-drawer').classList.add('show');
  }
  async function fulfill(o){await db.collection('orders').doc(o.firestoreId).update({status:'fulfilled',fulfilledAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});if(window.adminUI)adminUI.showToast('Order marked fulfilled','success','Order updated')}
  function openCancel(){var modal=document.getElementById('cancel-order-modal');if(!modal){modal=document.createElement('div');modal.id='cancel-order-modal';modal.className='modal-backdrop d-none';modal.innerHTML='<div class="modal" style="max-width:480px"><div class="modal-header"><h3 class="modal-title">Cancel Order?</h3><button class="modal-close" type="button"><i class="fas fa-times"></i></button></div><div class="modal-body"><p>This changes the order status to cancelled.</p><label class="inventory-return-option"><input type="checkbox" id="returnOrderInventory" checked><span><strong>Return ordered items to inventory</strong><small>Restores reserved stock transactionally and records each adjustment. This can only happen once.</small></span></label><div id="cancelOrderError" class="order-action-error"></div></div><div class="modal-footer"><button class="btn btn-secondary modal-close" type="button">Keep Order</button><button class="btn btn-danger" id="confirmCancelOrder" type="button">Cancel Order</button></div></div>';document.body.appendChild(modal);modal.addEventListener('click',function(e){if(e.target===modal||e.target.closest('.modal-close'))modal.classList.add('d-none')});document.getElementById('confirmCancelOrder').addEventListener('click',cancelOrder)}modal.classList.remove('d-none')}
  async function cancelOrder(){var btn=document.getElementById('confirmCancelOrder'),err=document.getElementById('cancelOrderError');btn.disabled=true;err.textContent='';try{await fbCancelOrder(active.firestoreId,document.getElementById('returnOrderInventory').checked);document.getElementById('cancel-order-modal').classList.add('d-none');document.getElementById('order-details-drawer').classList.remove('show');if(window.adminUI)adminUI.showToast('Order cancelled safely','success','Inventory updated')}catch(e){err.textContent=e.message||'Order could not be cancelled.'}finally{btn.disabled=false}}
  function invoice(o){window.location.href='/api/orders/invoice?orderId='+encodeURIComponent(o.firestoreId)}
  function openEmailInvoice(o){var recipient=o.customerEmail||(o.customer&&o.customer.email)||'';var modal=document.getElementById('email-invoice-modal');if(!modal){modal=document.createElement('div');modal.id='email-invoice-modal';modal.className='modal-backdrop d-none';modal.innerHTML='<div class="modal" style="max-width:440px"><div class="modal-header"><h3 class="modal-title">Send Invoice</h3><button class="modal-close" type="button"><i class="fas fa-times"></i></button></div><div class="modal-body"><p>Send invoice to:</p><p><strong id="invoiceRecipient"></strong></p><div id="invoiceEmailError" class="order-action-error"></div></div><div class="modal-footer"><button class="btn btn-secondary modal-close" type="button">Cancel</button><button class="btn btn-primary" id="confirmEmailInvoice" type="button">Send Invoice</button></div></div>';document.body.appendChild(modal);modal.addEventListener('click',function(e){if(e.target===modal||e.target.closest('.modal-close'))modal.classList.add('d-none')});document.getElementById('confirmEmailInvoice').addEventListener('click',sendInvoice)}document.getElementById('invoiceRecipient').textContent=recipient;document.getElementById('invoiceEmailError').textContent='';modal.classList.remove('d-none')}
  async function sendInvoice(){var btn=document.getElementById('confirmEmailInvoice'),err=document.getElementById('invoiceEmailError');btn.disabled=true;btn.textContent='Sending…';try{var response=await fetch('/api/orders/invoice-email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({orderId:active.firestoreId,resend:true})});if(!response.ok)throw new Error('Invoice could not be sent. Check email configuration.');document.getElementById('email-invoice-modal').classList.add('d-none');if(window.adminUI)adminUI.showToast('Invoice sent successfully','success','Email sent')}catch(e){err.textContent=e.message}finally{btn.disabled=false;btn.textContent='Send Invoice'}}
  async function confirmPayment(o){await db.collection('orders').doc(o.firestoreId).update({paymentStatus:'payment_confirmed','payment.status':'payment_confirmed',paymentConfirmedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});if(window.adminUI)adminUI.showToast('Payment confirmed','success','Order updated');document.getElementById('order-details-drawer').classList.remove('show')}
  document.addEventListener('DOMContentLoaded',function(){document.getElementById('ordersBody').innerHTML='<tr><td colspan="8">Loading orders…</td></tr>';document.querySelectorAll('.tab-link').forEach(function(a){a.addEventListener('click',function(e){e.preventDefault();filter=a.getAttribute('href').replace('#','').replace('-orders','');document.querySelectorAll('.tab-link').forEach(function(x){x.classList.toggle('active',x===a)});render()})});document.querySelector('.topbar-search input')?.addEventListener('input',render);db.collection('orders').orderBy('createdAt','desc').onSnapshot(function(s){orders=[];s.forEach(function(d){orders.push(Object.assign({firestoreId:d.id},d.data()))});render()},function(){document.getElementById('ordersBody').innerHTML='<tr><td colspan="8">Unable to load orders.</td></tr>'})});
  document.addEventListener('click',function(e){var b=e.target.closest('[data-live-action]');if(b){e.preventDefault();var o=b.dataset.id?orders.find(function(x){return x.firestoreId===b.dataset.id}):active;if(!o)return;if(b.dataset.liveAction==='view')drawer(o);if(b.dataset.liveAction==='fulfill')fulfill(o);if(b.dataset.liveAction==='cancel')openCancel();if(b.dataset.liveAction==='invoice')invoice(o);if(b.dataset.liveAction==='email-invoice')openEmailInvoice(o);if(b.dataset.liveAction==='confirm-payment')confirmPayment(o)}if(e.target.closest('.drawer-close'))document.getElementById('order-details-drawer').classList.remove('show')},true);
})();
