(function(){
  'use strict';
  var orders=[],active=null,filter='all';
  function esc(v){var d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
  function date(v){if(!v)return null;if(typeof v.toDate==='function')return v.toDate();if(v.seconds)return new Date(v.seconds*1000);return new Date(v)}
  function money(v){return'TTD $'+Number(v||0).toFixed(2)}
  function label(v){return String(v||'pending').replace(/_/g,' ').replace(/\b\w/g,function(c){return c.toUpperCase()})}
  function count(o){return(o.items||[]).reduce(function(s,i){return s+Number(i.quantity||1)},0)}
  function paymentStatus(o){return o.paymentStatus||(o.payment&&o.payment.status)||'pending'}
  function paymentProof(o){var payment=o.payment||{};return payment.proofUrl||o.paymentProofUrl||''}
  function render(){
    var q=(document.querySelector('.topbar-search input')?.value||'').toLowerCase();
    var list=orders.filter(function(o){var hay=[o.orderNumber,o.customerName,o.customerEmail,o.customerPhone].join(' ').toLowerCase();return(filter==='all'||o.status===filter)&&(!q||hay.includes(q))});
    ['all','pending','fulfilled','cancelled'].forEach(function(s){var el=document.getElementById(s+'Count');if(el)el.textContent=s==='all'?orders.length:orders.filter(function(o){return o.status===s}).length});
    document.getElementById('ordersBody').innerHTML=list.length?list.map(function(o){var created=date(o.createdAt),pay=paymentStatus(o);return '<tr class="order-row"><td><strong>#'+esc(o.orderNumber||o.firestoreId)+'</strong></td><td>'+esc(o.customerName||(o.customer&&o.customer.name)||'—')+'<small class="order-cell-sub">'+esc(o.customerEmail||(o.customer&&o.customer.email)||'')+'</small></td><td>'+count(o)+'</td><td><strong>'+money(o.total||(o.pricing&&o.pricing.total))+'</strong></td><td><span class="badge '+(pay==='paid'||pay==='verified'||pay==='payment_confirmed'?'success':'pending')+'">'+esc(label(pay))+'</span></td><td><span class="badge '+(o.status==='fulfilled'?'success':o.status==='cancelled'?'danger':'pending')+'">'+esc(label(o.status))+'</span></td><td>'+esc(created?created.toLocaleString('en-TT',{dateStyle:'medium',timeStyle:'short'}):'Pending sync')+'</td><td><button class="btn btn-sm btn-primary" data-live-action="view" data-id="'+esc(o.firestoreId)+'">View</button></td></tr>'}).join(''):'<tr><td colspan="8"><div class="admin-empty-state"><h3>No orders found</h3><p>New customer orders will appear here automatically.</p></div></td></tr>';
  }
  async function drawer(o){
    active=o;var c=o.customer||{},del=o.delivery||{},pay=o.payment||{},p=o.pricing||{},created=date(o.createdAt);var map=del.latitude&&del.longitude?'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(del.latitude+','+del.longitude):'';
    var history=[];try{var snap=await db.collection('inventoryTransactions').where('orderId','==',o.firestoreId).get();snap.forEach(function(d){history.push(d.data())})}catch(e){console.warn('Inventory history unavailable',e)}
    var items=(o.items||[]).map(function(i){var original=Number(i.baseUnitPrice||i.unitPrice||0),sale=Number(i.unitPrice||0),discount=original>sale?'<small><s>'+money(original)+'</s> · '+Number(i.discountRate||0)+'% off</small>':'';return '<div class="order-item"><div class="order-item-thumb">'+(i.image?'<img src="'+esc(i.image)+'" alt="">':'<i class="fas fa-seedling"></i>')+'</div><div class="item-info"><div class="item-name">'+esc(i.productName||i.name)+'</div><small>'+esc(i.category||'Plant')+' · '+money(sale)+' each</small>'+discount+'</div><div class="item-quantity">×'+Number(i.quantity||1)+'</div><div class="item-price">'+money(i.lineTotal||sale*Number(i.quantity||1))+'</div></div>'}).join('');
    var events=history.length?history.map(function(h){return '<div class="inventory-event"><i class="fas fa-boxes-stacked"></i><div><strong>'+esc(label(h.type))+'</strong><span>'+esc(h.productName)+' · '+(Number(h.adjustment)>0?'+':'')+Number(h.adjustment||0)+' ('+h.before+' → '+h.after+')</span></div></div>'}).join(''):'<p class="order-muted">No inventory events recorded for this order.</p>';
    var invoiceEmail=o.invoiceEmail||{status:'not_sent'},sent=date(invoiceEmail.sentAt);var invoiceMeta='<p><strong>Invoice email:</strong> <span class="badge '+(invoiceEmail.status==='sent'?'success':invoiceEmail.status==='failed'?'danger':'pending')+'">'+esc(label(invoiceEmail.status||'not_sent'))+'</span></p>'+(invoiceEmail.recipient?'<p>Sent to: '+esc(invoiceEmail.recipient)+'</p>':'')+(sent?'<p>Sent: '+esc(sent.toLocaleString('en-TT',{dateStyle:'medium',timeStyle:'short'}))+'</p>':'');
    var proof=paymentProof(o),proofPreview=proof?'<div class="payment-proof-preview">'+(/\.(pdf)(\?|$)/i.test(proof)?'<i class="fas fa-file-pdf" style="font-size:2rem;color:var(--danger)"></i>':'<img src="'+esc(proof)+'" alt="Payment proof">')+'<a href="'+esc(proof)+'" target="_blank" rel="noopener">View payment proof</a></div>':'';
    var controls='<section class="order-section"><h5>Update order</h5><div class="order-status-controls"><div class="status-control"><label for="adminPaymentStatus">Payment status</label><select id="adminPaymentStatus" class="form-control form-select"><option value="awaiting_payment">Awaiting Payment</option><option value="proof_submitted">Proof Submitted</option><option value="payment_confirmed">Payment Confirmed</option><option value="payment_failed">Payment Failed</option><option value="refunded">Refunded</option></select></div><div class="status-control"><label for="adminFulfilmentStatus">Fulfilment status</label><select id="adminFulfilmentStatus" class="form-control form-select"><option value="pending">Pending</option><option value="processing">Processing</option><option value="ready">Ready for Pickup / Delivery</option><option value="fulfilled">Fulfilled / Successful</option><option value="cancelled">Cancelled</option></select></div></div><button type="button" class="btn btn-primary" style="margin-top:12px" data-live-action="save-status"><i class="fas fa-check"></i> Save Status</button><div class="payment-proof-box"><strong>Payment proof (optional)</strong><p>Attach a screenshot or PDF received from the customer.</p>'+proofPreview+'<div class="proof-upload-actions"><input type="file" id="adminPaymentProof" accept="image/jpeg,image/png,image/webp,application/pdf" hidden><button type="button" class="btn btn-sm btn-secondary" onclick="document.getElementById(\'adminPaymentProof\').click()"><i class="fas fa-image"></i> '+(proof?'Replace':'Add')+' Picture / Proof</button><small id="paymentProofStatus"></small></div></div></section>';
    document.getElementById('orderDrawerBody').innerHTML='<div class="order-details"><div class="order-header"><div><span class="admin-eyebrow">Order</span><h4>#'+esc(o.orderNumber||o.firestoreId)+'</h4><small>'+esc(created?created.toLocaleString('en-TT',{dateStyle:'full',timeStyle:'short'}):'Pending sync')+'</small></div><span class="badge '+(o.status==='cancelled'?'danger':o.status==='fulfilled'?'success':'pending')+'">'+esc(label(o.status))+'</span></div>'+controls+'<div class="order-detail-grid"><section class="order-section"><h5>Customer</h5><p><strong>'+esc(o.customerName||c.name)+'</strong></p><p>'+esc(o.customerEmail||c.email)+'</p><p>'+esc(o.customerPhone||c.phone)+'</p></section><section class="order-section"><h5>Payment & invoice</h5><p><strong>'+esc(label(o.paymentMethod||pay.method))+'</strong></p><p><span class="badge '+(paymentStatus(o)==='payment_confirmed'?'success':'pending')+'">'+esc(label(paymentStatus(o)))+'</span></p>'+invoiceMeta+(pay.proofReference?'<p>Proof submitted</p>':'')+'</section><section class="order-section"><h5>Delivery</h5><p><strong>'+esc(label(del.method||o.deliveryOption))+'</strong></p><p>'+esc([del.address||o.address,del.city||o.city,del.region||o.region].filter(Boolean).join(', ')||'Farm pickup')+'</p>'+(map?'<a class="btn btn-sm btn-secondary" href="'+map+'" target="_blank" rel="noopener">Open map</a>':'')+'</section><section class="order-section"><h5>Fulfilment</h5><p>Status: <strong>'+esc(label(o.status))+'</strong></p><p>'+esc(o.notes||'No order notes.')+'</p></section></div><section class="order-section"><h5>Items</h5>'+items+'</section><div class="order-total"><div><span>Subtotal</span><span>'+money(p.subtotal||o.subtotal)+'</span></div><div><span>Promotion savings</span><span>−'+money(p.discount||o.discount)+'</span></div><div><span>Delivery</span><span>'+money(p.delivery||o.deliveryFee)+'</span></div><div class="total"><span>Total</span><span>'+money(p.total||o.total)+'</span></div></div><section class="order-section"><h5>Inventory history</h5>'+events+'</section></div>';
    document.getElementById('adminPaymentStatus').value=paymentStatus(o);document.getElementById('adminFulfilmentStatus').value=o.status||'pending';document.getElementById('adminPaymentProof').addEventListener('change',uploadPaymentProof);
    var footer=document.querySelector('#order-details-drawer .drawer-footer');footer.innerHTML='<button type="button" class="btn btn-secondary drawer-close">Close</button><button type="button" class="btn btn-secondary" data-live-action="invoice"><i class="fas fa-file-pdf"></i> Download Invoice</button><button type="button" class="btn btn-secondary" data-live-action="email-invoice"><i class="fas fa-envelope"></i> '+(invoiceEmail.status==='sent'?'Resend':'Email')+' Invoice</button>'+(paymentStatus(o)!=='payment_confirmed'?'<button type="button" class="btn btn-primary" data-live-action="confirm-payment"><i class="fas fa-money-check"></i> Confirm Payment</button>':'')+(o.status==='pending'?'<button type="button" class="btn btn-danger" data-live-action="cancel"><i class="fas fa-ban"></i> Cancel Order</button><button type="button" class="btn btn-success" data-live-action="fulfill"><i class="fas fa-check"></i> Fulfil Order</button>':'');
    document.getElementById('order-details-drawer').classList.add('open');
  }
  async function fulfill(o){await db.collection('orders').doc(o.firestoreId).update({status:'fulfilled',fulfilledAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});if(window.adminUI)adminUI.showToast('Order marked fulfilled','success','Order updated')}
  async function saveOrderStatus(o){
    var payment=document.getElementById('adminPaymentStatus').value,fulfilment=document.getElementById('adminFulfilmentStatus').value;
    if(fulfilment==='cancelled'&&o.status!=='cancelled'){openCancel();return}
    var update={paymentStatus:payment,'payment.status':payment,status:fulfilment,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};
    if(payment==='payment_confirmed'&&paymentStatus(o)!=='payment_confirmed')update.paymentConfirmedAt=firebase.firestore.FieldValue.serverTimestamp();
    if(fulfilment==='fulfilled'&&o.status!=='fulfilled')update.fulfilledAt=firebase.firestore.FieldValue.serverTimestamp();
    await db.collection('orders').doc(o.firestoreId).update(update);
    Object.assign(o,{paymentStatus:payment,status:fulfilment});o.payment=Object.assign({},o.payment||{},{status:payment});
    if(window.adminUI)adminUI.showToast('Order status saved','success','Payment and fulfilment updated');
    await drawer(o);
  }
  async function uploadPaymentProof(e){
    var file=e.target.files&&e.target.files[0],status=document.getElementById('paymentProofStatus');if(!file||!active)return;
    var allowed=['image/jpeg','image/png','image/webp','application/pdf'];
    if(!allowed.includes(file.type)){status.textContent='Choose a JPG, PNG, WEBP or PDF file.';e.target.value='';return}
    if(file.size>8*1024*1024){status.textContent='File must be 8 MB or smaller.';e.target.value='';return}
    status.textContent='Uploading…';e.target.disabled=true;
    try{
      if(!firebase.storage)throw new Error('File storage is not available.');
      var safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'-'),ref=firebase.storage().ref('order-payment-proofs/'+active.firestoreId+'/'+Date.now()+'-'+safeName);
      await ref.put(file,{contentType:file.type});var url=await ref.getDownloadURL(),current=paymentStatus(active),next=current==='payment_confirmed'?current:'proof_submitted';
      await db.collection('orders').doc(active.firestoreId).update({'payment.proofReference':url,'payment.proofUrl':url,'payment.proofFileName':file.name,'payment.proofUploadedAt':firebase.firestore.FieldValue.serverTimestamp(),paymentProofUrl:url,paymentStatus:next,'payment.status':next,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});
      active.payment=Object.assign({},active.payment||{},{proofReference:url,proofUrl:url,proofFileName:file.name,status:next});active.paymentProofUrl=url;active.paymentStatus=next;
      if(window.adminUI)adminUI.showToast('Payment proof added','success','Order updated');await drawer(active);
    }catch(error){status.textContent=error.message||'Payment proof could not be uploaded.';e.target.disabled=false}
  }
  function openCancel(){var modal=document.getElementById('cancel-order-modal');if(!modal){modal=document.createElement('div');modal.id='cancel-order-modal';modal.className='modal-backdrop d-none';modal.innerHTML='<div class="modal" style="max-width:480px"><div class="modal-header"><h3 class="modal-title">Cancel Order?</h3><button class="modal-close" type="button"><i class="fas fa-times"></i></button></div><div class="modal-body"><p>This changes the order status to cancelled.</p><label class="inventory-return-option"><input type="checkbox" id="returnOrderInventory" checked><span><strong>Return ordered items to inventory</strong><small>Restores reserved stock transactionally and records each adjustment. This can only happen once.</small></span></label><div id="cancelOrderError" class="order-action-error"></div></div><div class="modal-footer"><button class="btn btn-secondary modal-close" type="button">Keep Order</button><button class="btn btn-danger" id="confirmCancelOrder" type="button">Cancel Order</button></div></div>';document.body.appendChild(modal);modal.addEventListener('click',function(e){if(e.target===modal||e.target.closest('.modal-close'))modal.classList.add('d-none')});document.getElementById('confirmCancelOrder').addEventListener('click',cancelOrder)}modal.classList.remove('d-none')}
  async function cancelOrder(){var btn=document.getElementById('confirmCancelOrder'),err=document.getElementById('cancelOrderError');btn.disabled=true;err.textContent='';try{await fbCancelOrder(active.firestoreId,document.getElementById('returnOrderInventory').checked);document.getElementById('cancel-order-modal').classList.add('d-none');document.getElementById('order-details-drawer').classList.remove('open');if(window.adminUI)adminUI.showToast('Order cancelled safely','success','Inventory updated')}catch(e){err.textContent=e.message||'Order could not be cancelled.'}finally{btn.disabled=false}}
  async function invoice(o){
    var button=document.querySelector('[data-live-action="invoice"]'),original=button&&button.innerHTML;
    if(button){button.disabled=true;button.innerHTML='<i class="fas fa-spinner fa-spin"></i> Preparing…'}
    try{
      var response=await fetch('/api/orders/invoice?orderId='+encodeURIComponent(o.firestoreId),{credentials:'same-origin'});
      if(!response.ok){var message=await response.text();throw new Error(message||'Invoice could not be generated.');}
      var blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');
      link.href=url;link.download='Rishis-Lily-Farm-'+(o.orderNumber||o.firestoreId)+'.pdf';document.body.appendChild(link);link.click();link.remove();setTimeout(function(){URL.revokeObjectURL(url)},1000);
      if(window.adminUI)adminUI.showToast('Invoice downloaded','success','PDF ready');
    }catch(error){if(window.adminUI)adminUI.showToast(error.message||'Invoice could not be downloaded.','error','Download failed');}
    finally{if(button){button.disabled=false;button.innerHTML=original}}
  }
  function openEmailInvoice(o){var recipient=o.customerEmail||(o.customer&&o.customer.email)||'';var modal=document.getElementById('email-invoice-modal');if(!modal){modal=document.createElement('div');modal.id='email-invoice-modal';modal.className='modal-backdrop d-none';modal.innerHTML='<div class="modal" style="max-width:440px"><div class="modal-header"><h3 class="modal-title">Send Invoice</h3><button class="modal-close" type="button"><i class="fas fa-times"></i></button></div><div class="modal-body"><p>Send invoice to:</p><p><strong id="invoiceRecipient"></strong></p><div id="invoiceEmailError" class="order-action-error"></div></div><div class="modal-footer"><button class="btn btn-secondary modal-close" type="button">Cancel</button><button class="btn btn-primary" id="confirmEmailInvoice" type="button">Send Invoice</button></div></div>';document.body.appendChild(modal);modal.addEventListener('click',function(e){if(e.target===modal||e.target.closest('.modal-close'))modal.classList.add('d-none')});document.getElementById('confirmEmailInvoice').addEventListener('click',sendInvoice)}document.getElementById('invoiceRecipient').textContent=recipient;document.getElementById('invoiceEmailError').textContent='';modal.classList.remove('d-none')}
  async function sendInvoice(){var btn=document.getElementById('confirmEmailInvoice'),err=document.getElementById('invoiceEmailError'),controller=new AbortController(),timer=setTimeout(function(){controller.abort()},30000);btn.disabled=true;btn.textContent='Sending…';err.textContent='';try{var response=await fetch('/api/orders/invoice-email',{method:'POST',credentials:'same-origin',signal:controller.signal,headers:{'content-type':'application/json'},body:JSON.stringify({orderId:active.firestoreId,resend:true})}),result=await response.json().catch(function(){return{}});if(!response.ok||result.status!=='sent'){var messages={EMAIL_NOT_CONFIGURED:'Email credentials are not configured in Vercel.',DELIVERY_FAILED:'The email provider rejected or could not complete delivery.'};throw new Error(messages[result.code]||result.error||'Invoice could not be sent.');}document.getElementById('email-invoice-modal').classList.add('d-none');active.invoiceEmail=Object.assign({},active.invoiceEmail||{},{status:'sent',recipient:result.recipient,sentAt:new Date().toISOString()});if(window.adminUI)adminUI.showToast('Invoice sent to '+result.recipient,'success','Email sent');await drawer(active)}catch(e){err.textContent=e.name==='AbortError'?'Email delivery timed out. Check the SMTP credentials in Vercel.':e.message}finally{clearTimeout(timer);btn.disabled=false;btn.textContent='Send Invoice'}}
  async function confirmPayment(o){await db.collection('orders').doc(o.firestoreId).update({paymentStatus:'payment_confirmed','payment.status':'payment_confirmed',paymentConfirmedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});if(window.adminUI)adminUI.showToast('Payment confirmed','success','Order updated');document.getElementById('order-details-drawer').classList.remove('open')}
  document.addEventListener('DOMContentLoaded',function(){document.getElementById('ordersBody').innerHTML='<tr><td colspan="8">Loading orders…</td></tr>';document.querySelectorAll('.tab-link').forEach(function(a){a.addEventListener('click',function(e){e.preventDefault();filter=a.getAttribute('href').replace('#','').replace('-orders','');document.querySelectorAll('.tab-link').forEach(function(x){x.classList.toggle('active',x===a)});render()})});document.querySelector('.topbar-search input')?.addEventListener('input',render);db.collection('orders').orderBy('createdAt','desc').onSnapshot(function(s){orders=[];s.forEach(function(d){orders.push(Object.assign({firestoreId:d.id},d.data()))});render()},function(){document.getElementById('ordersBody').innerHTML='<tr><td colspan="8">Unable to load orders.</td></tr>'})});
  document.addEventListener('click',function(e){var b=e.target.closest('[data-live-action]');if(b){e.preventDefault();var o=b.dataset.id?orders.find(function(x){return x.firestoreId===b.dataset.id}):active;if(!o)return;if(b.dataset.liveAction==='view')drawer(o);if(b.dataset.liveAction==='fulfill')fulfill(o);if(b.dataset.liveAction==='cancel')openCancel();if(b.dataset.liveAction==='invoice')invoice(o);if(b.dataset.liveAction==='email-invoice')openEmailInvoice(o);if(b.dataset.liveAction==='confirm-payment')confirmPayment(o);if(b.dataset.liveAction==='save-status')saveOrderStatus(o)}if(e.target.closest('.drawer-close'))document.getElementById('order-details-drawer').classList.remove('open')},true);
})();
