(function(){
  'use strict';
  var allFAQs=[],allSectionMeta=[],currentFilter='all';
  var sections=document.getElementById('faqSections'),filters=document.getElementById('categoryFilters'),search=document.getElementById('faqSearch'),clear=document.getElementById('searchClear'),empty=document.getElementById('noResults'),count=document.getElementById('faqCount'),title=document.getElementById('visibleCategoryTitle');
  function esc(value){var element=document.createElement('div');element.textContent=value==null?'':String(value);return element.innerHTML;}
  function formatAnswer(value){var safe=esc(value).replace(/\r?\n/g,'<br>');safe=safe.replace(/(https?:\/\/[^\s<]+)/g,'<a href="$1" target="_blank" rel="noopener noreferrer">$1</a>');safe=safe.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');safe=safe.replace(/([\w.+-]+@[\w.-]+\.[A-Za-z]{2,})/g,'<a href="mailto:$1">$1</a>');return safe;}
  function sectionKey(value){return String(value||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'general';}
  function sectionMeta(name){return allSectionMeta.find(function(section){return section.name===name||section.id===sectionKey(name);})||{name:name,status:'published',order:9999};}
  function categories(){return Array.from(new Set(allFAQs.map(function(item){return item.section;}).filter(Boolean))).sort(function(a,b){return (Number(sectionMeta(a).order)||9999)-(Number(sectionMeta(b).order)||9999);});}
  function buildFilters(){var cats=categories();filters.innerHTML='<button class="category-filter is-active" type="button" data-filter="all" aria-pressed="true"><i class="fas fa-list" aria-hidden="true"></i><span>All Questions</span><b>'+allFAQs.length+'</b></button>'+cats.map(function(cat){var total=allFAQs.filter(function(item){return item.section===cat;}).length;return '<button class="category-filter" type="button" data-filter="'+esc(cat)+'" aria-pressed="false"><i class="fas fa-seedling" aria-hidden="true"></i><span>'+esc(cat)+'</span><b>'+total+'</b></button>';}).join('');filters.querySelectorAll('button').forEach(function(button){button.addEventListener('click',function(){currentFilter=button.dataset.filter;filters.querySelectorAll('button').forEach(function(item){var active=item===button;item.classList.toggle('is-active',active);item.setAttribute('aria-pressed',String(active));});title.textContent=currentFilter==='all'?'All Questions':currentFilter;render();window.requestAnimationFrame(function(){var target=currentFilter==='all'?document.querySelector('.faq-content__heading'):sections.querySelector('.faq-section');if(target)target.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});});});});}
  function matches(item){var term=search.value.trim().toLowerCase(),inCategory=currentFilter==='all'||item.section===currentFilter,inSearch=!term||String(item.question||'').toLowerCase().includes(term)||String(item.answer||'').toLowerCase().includes(term);return inCategory&&inSearch;}
  function render(){var visible=allFAQs.filter(matches),grouped={};visible.forEach(function(item){if(!grouped[item.section])grouped[item.section]=[];grouped[item.section].push(item);});sections.innerHTML=Object.keys(grouped).sort(function(a,b){return(Number(sectionMeta(a).order)||9999)-(Number(sectionMeta(b).order)||9999);}).map(function(sectionName){var metadata=sectionMeta(sectionName);return '<section class="faq-section" data-category="'+esc(sectionName)+'"><h3 class="faq-section__title"><i class="fas '+esc(metadata.icon||'fa-seedling')+'" aria-hidden="true"></i>'+esc(sectionName)+'</h3>'+grouped[sectionName].sort(function(a,b){return(Number(a.order)||0)-(Number(b.order)||0);}).map(function(item){return '<article class="faq-item"><button class="faq-question" type="button" aria-expanded="false"><span>'+esc(item.question)+'</span><span class="faq-toggle" aria-hidden="true"></span></button><div class="faq-answer"><div class="faq-answer__inner"><div class="faq-answer__content">'+formatAnswer(item.answer)+'</div></div></div></article>';}).join('')+'</section>';}).join('');count.textContent=visible.length+' question'+(visible.length===1?'':'s');empty.hidden=visible.length!==0;sections.hidden=visible.length===0;bindAccordions();}
  function bindAccordions(){sections.querySelectorAll('.faq-question').forEach(function(button){button.addEventListener('click',function(){var item=button.closest('.faq-item'),opening=!item.classList.contains('is-open');sections.querySelectorAll('.faq-item.is-open').forEach(function(openItem){openItem.classList.remove('is-open');openItem.querySelector('.faq-question').setAttribute('aria-expanded','false');});if(opening){item.classList.add('is-open');button.setAttribute('aria-expanded','true');}});});}
  async function load(){try{var results=await Promise.all([db.collection('faqs').where('status','==','published').get(),db.collection('faqSections').get()]),items=[];results[0].forEach(function(doc){items.push(Object.assign({id:doc.id},doc.data()));});results[1].forEach(function(doc){allSectionMeta.push(Object.assign({id:doc.id},doc.data()));});items.forEach(function(item,index){if(!allSectionMeta.some(function(section){return section.name===item.section||section.id===sectionKey(item.section);})){allSectionMeta.push({id:sectionKey(item.section),name:item.section,icon:item.sectionIcon||'fa-seedling',status:'published',order:1000+index});}});allFAQs=items.filter(function(item){return sectionMeta(item.section).status!=='draft';});buildFilters();render();}catch(error){console.error('Failed to load FAQs:',error);sections.innerHTML='<div class="no-results"><h3>Unable to load questions right now.</h3><p>Please refresh the page or contact us for help.</p></div>';count.textContent='Unavailable';}}
  search.addEventListener('input',function(){clear.hidden=!search.value;render();});clear.addEventListener('click',function(){search.value='';clear.hidden=true;render();search.focus();});
  fetch('src/components/navbar.html?v=20260927').then(function(response){return response.text();}).then(function(html){document.getElementById('navbar').innerHTML=html;if(typeof updateCartBadge==='function')updateCartBadge();if(typeof initializeMobileMenu==='function')initializeMobileMenu();var links=document.querySelectorAll('#navbar a[href="faq.html"]');if(links.length)links[links.length-1].classList.add('active');});
  load();
})();
