(function(){
  'use strict';
  var contextProduct=null;
  function esc(v){var d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
  function stars(n){return '<span class="review-stars" aria-label="'+n+' out of 5 stars">'+[1,2,3,4,5].map(function(i){return '<span class="'+(i<=n?'on':'')+'">★</span>'}).join('')+'</span>'}
  function date(v){if(!v)return'';if(typeof v.toDate==='function')v=v.toDate();else if(v.seconds)v=new Date(v.seconds*1000);else v=new Date(v);return isNaN(v)?'':v.toLocaleDateString('en-TT',{year:'numeric',month:'long',day:'numeric'})}
  function ensureModal(){if(document.getElementById('reviewModal'))return;document.body.insertAdjacentHTML('beforeend','<div class="review-modal" id="reviewModal" hidden><div class="review-modal__panel" role="dialog" aria-modal="true" aria-labelledby="reviewModalTitle"><button class="review-modal__close" type="button" aria-label="Close">×</button><p class="detail-eyebrow">Share your experience</p><h2 id="reviewModalTitle">Write a Review</h2><form id="reviewForm"><input name="website" tabindex="-1" autocomplete="off" class="review-honeypot"><fieldset class="review-type"><legend>Review type</legend><label><input type="radio" name="reviewType" value="product" checked> Product Review</label><label><input type="radio" name="reviewType" value="general"> General Experience</label></fieldset><label class="review-product-field">Product *<select name="productId" id="reviewProduct"></select></label><fieldset class="rating-picker"><legend>Your rating *</legend><div>'+[1,2,3,4,5].map(function(i){return '<button type="button" data-rating="'+i+'" aria-label="'+i+' star'+(i===1?'':'s')+'">☆</button>'}).join('')+'</div><input type="hidden" name="rating" required></fieldset><label>Your name *<input name="customerName" minlength="2" maxlength="80" required></label><label>Email *<input name="customerEmail" type="email" maxlength="160" required></label><label>Your review *<textarea name="reviewText" minlength="10" maxlength="1500" required></textarea></label><p class="review-note">Reviews are checked before appearing publicly. Photo uploads are unavailable until secure Storage rules are configured.</p><div class="review-error" aria-live="polite"></div><button class="review-submit" type="submit">Submit Review</button></form><div class="review-success" hidden><span>✓</span><h3>Thanks for your review!</h3><p>Your review has been submitted and is awaiting approval.</p><button type="button" class="review-done">Done</button></div></div></div>');
    var modal=document.getElementById('reviewModal'),form=document.getElementById('reviewForm');
    modal.addEventListener('click',function(e){if(e.target===modal||e.target.closest('.review-modal__close')||e.target.closest('.review-done'))close()});
    modal.querySelectorAll('[data-rating]').forEach(function(btn){btn.addEventListener('click',function(){var n=Number(btn.dataset.rating);form.rating.value=n;modal.querySelectorAll('[data-rating]').forEach(function(b){b.textContent=Number(b.dataset.rating)<=n?'★':'☆';b.classList.toggle('on',Number(b.dataset.rating)<=n)})})});
    form.addEventListener('change',function(e){if(e.target.name==='reviewType')modal.querySelector('.review-product-field').hidden=e.target.value==='general'});
    form.addEventListener('submit',submit);
  }
  function productOptions(){var list=Object.values(window.products||{});return '<option value="">Choose a product</option>'+list.map(function(p){return '<option value="'+esc(p.firestoreId||p.id)+'" data-name="'+esc(p.name)+'">'+esc(p.name)+'</option>'}).join('')}
  function open(product,general){ensureModal();contextProduct=product||null;var modal=document.getElementById('reviewModal'),form=document.getElementById('reviewForm'),select=document.getElementById('reviewProduct');form.reset();form.hidden=false;modal.querySelector('.review-success').hidden=true;form.reviewType.value=general?'general':'product';modal.querySelector('.review-product-field').hidden=!!general;modal.querySelectorAll('[data-rating]').forEach(function(b){b.textContent='☆';b.classList.remove('on')});select.innerHTML=productOptions();if(product)select.value=product.firestoreId||product.id||'';modal.hidden=false;document.body.classList.add('review-modal-open')}
  function close(){var modal=document.getElementById('reviewModal');if(modal)modal.hidden=true;document.body.classList.remove('review-modal-open')}
  async function submit(e){e.preventDefault();var form=e.currentTarget,button=form.querySelector('button[type=submit]'),error=form.querySelector('.review-error'),data=Object.fromEntries(new FormData(form).entries()),selected=form.querySelector('#reviewProduct option:checked');if(!data.rating){error.textContent='Please choose a star rating.';return}if(data.reviewType==='product'&&!data.productId){error.textContent='Please choose a product.';return}data.productName=selected?selected.dataset.name||'':'';button.disabled=true;button.textContent='Submitting…';error.textContent='';try{var response=await fetch('/api/reviews/submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}),result=await response.json();if(!response.ok)throw new Error(result.error||'Review could not be submitted.');form.hidden=true;form.closest('.review-modal__panel').querySelector('.review-success').hidden=false}catch(err){error.textContent=err.message}finally{button.disabled=false;button.textContent='Submit Review'}}
  async function renderPublic(product){var section=document.getElementById('customerReviews'),list=document.getElementById('publicReviewList');if(!section||!list||!window.db)return;try{var snap=await db.collection('reviews').where('status','==','published').get(),reviews=[];snap.forEach(function(doc){var r=Object.assign({id:doc.id},doc.data());if(r.reviewType!=='general'&&(r.productId===product.firestoreId||r.productId===product.id||r.productName===product.name))reviews.push(r)});reviews.sort(function(a,b){return new Date(b.createdAt)-new Date(a.createdAt)});var average=reviews.length?reviews.reduce(function(s,r){return s+Number(r.rating||0)},0)/reviews.length:0;document.getElementById('reviewAverage').textContent=reviews.length?average.toFixed(1):'—';document.getElementById('reviewCount').textContent=reviews.length?'Based on '+reviews.length+' review'+(reviews.length===1?'':'s'):'No reviews yet';list.innerHTML=reviews.length?reviews.map(function(r){return '<article class="public-review"><div>'+stars(Number(r.rating))+' <strong>'+Number(r.rating).toFixed(1)+'</strong></div><div class="public-review__meta"><strong>'+esc(r.customerName)+'</strong>'+(r.verifiedPurchase?'<span>✓ Verified Purchase</span>':'')+'<time>'+esc(date(r.createdAt))+'</time></div><p>“'+esc(r.reviewText)+'”</p>'+(r.adminReply?'<div class="farm-response"><strong>Response from Rishi\'s Lily Farm</strong><p>'+esc(r.adminReply)+'</p></div>':'')+'</article>'}).join(''):'<div class="reviews-empty"><strong>No customer reviews yet.</strong><p>Be the first to share how your plant is doing.</p></div>';section.hidden=false}catch(error){console.warn('Reviews unavailable:',error.message)}}
  document.addEventListener('click',function(e){var btn=e.target.closest('[data-write-review]');if(btn){e.preventDefault();open(btn.dataset.general==='true'?null:contextProduct,btn.dataset.general==='true')}});
  window.reviewUI={open:open,renderPublic:renderPublic,setProduct:function(p){contextProduct=p}};
  document.addEventListener('DOMContentLoaded',ensureModal);
}());
